version: '3.5'
services:
  mongodb:
    image: mongo
    restart: always
    container_name: what-is-watch-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
    ports:
      - 27027:27017
    volumes:
      - ./mongodb:/data/db

  mongodb-express:
    image: mongo-express
    restart: always
    container_name: what-is-watch-express
    ports:
      - 8008:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://admin:test@mongodb:27017/
